# SPDX-License-Identifier: MPL-2.0
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: collabora-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Rash419/argocd-collabora.git
        revision: HEAD
        files:
          - path: "values.yaml"
  template:
    metadata:
      name: collabora
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        # Helm chart from registry
        - repoURL: registry.gitlab.collabora.com
          chart: productivity/cool-controller-registry/helm-charts/collabora-online-umbrella
          targetRevision: "*"
          helm:
            valueFiles:
              - $values/values.yaml
            releaseName: collabora
        # Git repo for values file
        - repoURL: https://github.com/Rash419/argocd-collabora.git
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: collabora
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
